[package]
name = "tracesets"
version = "0.1.0"
authors = ["jannes <jannes.dev@posteo.net>"]
edition = "2018"


[features]
default = []
c_repr = []

[dependencies]
tracesets_sys = { path = "../tracesets-sys" }

